general:
    version: 2
    format: html
    path: report
    keepUnusedPlots: 7
    selfContained: false
    noDate: false
summary: [ chord, venn, upset ]
features:
    retMin: true
    chromatograms:
        large: true
        small: true
        features: false
        intMax: eic
    intensityPlots: false
    aggregateConcs: mean
    aggregateTox: mean
MSPeakLists:
    spectra: true
formulas:
    include: true
    normalizeScores: max
    exclNormScores: [ ]
    topMost: 25
compounds:
    normalizeScores: max
    exclNormScores: [ score, individualMoNAScore, annoTypeCount, annotHitCount, libMatch ]
    onlyUsedScorings: true
    topMost: 25
TPs:
    graphs: true
    graphStructuresMax: 25
internalStandards:
    graph: true
