# SPDX-FileCopyrightText: 2016-2024 Rick Helmus <r.helmus@uva.nl>
#
# SPDX-License-Identifier: GPL-3.0-only

version = 1

[[annotations]]
path = ["inst/**", "docs/**", "man/**", "man-roxygen/**", "tests/**", "vignettes/**", "NAMESPACE", "*.md",
        "DESCRIPTION", "R/**", "src/*", "docker/**", "*", "data-raw/**", ".circleci/config.yml",
        ".github/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2016-204 Rick Helmus <r.helmus@uva.nl>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = ["src/GenForm-svn/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2015 M Meringer"
SPDX-License-Identifier = "LGPL-2.0-only"

[[annotations]]
path = ["src/pugixml/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2006-2022 Arseny Kapoulkine <arseny.kapoulkine@gmail.com>"
SPDX-License-Identifier = "MIT"
