# SPDX-FileCopyrightText: 2016-2024 Rick Helmus <r.helmus@uva.nl>
#
# SPDX-License-Identifier: GPL-3.0-only

version = 1

[[annotations]]
path = ["inst/**", "docs/**", "man/**", "man-roxygen/**", "tests/**", "vignettes/**", "NAMESPACE", "*.md",
        "DESCRIPTION", "R/**", "src/*", "docker/**", "*", "data-raw/**", ".circleci/config.yml",
        ".github/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2016-2025 Rick Helmus <r.helmus@uva.nl>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = ["src/GenForm-svn/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2015 M Meringer"
SPDX-License-Identifier = "LGPL-2.0-only"

[[annotations]]
path = ["src/pugixml/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2006-2022 Arseny Kapoulkine <arseny.kapoulkine@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["src/cpp-base64/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2004-2017 René Nyffenegger"
SPDX-License-Identifier = "Zlib"

[[annotations]]
path = ["src/hclust-cpp/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2020 Christoph Dalitz and 2011 Daniel Müllner"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = ["src/opentims++/sqlite/**"]
precedence = "closest"
SPDX-FileCopyrightText = ""
SPDX-License-Identifier = "blessing"

[[annotations]]
path = ["src/opentims++/zstd/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2016-2020 Yann Collet"
SPDX-License-Identifier = "BSD-3-Clause OR GPL-2.0-only"

[[annotations]]
path = ["src/opentims++/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2016-2020 Yann Collet"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["src/StreamCraft/simdutf/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2021 The simdutf authors"
SPDX-License-Identifier = "Apache-2.0 OR MIT"

[[annotations]]
path = ["src/StreamCraft/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2025 StreamFind"
SPDX-License-Identifier = "MIT"

